[import]

description = "Import model evaluation results"
exec = "python import.py"
config = "import.py"
sourcecode = ["-**/.* dir", "import.py", "_util.py"]
listing.description = ["model", "eval"]
output-summary = "Summarizing results\\n(.*)"
