[import]

exec = "python import_results.py"
description = "Import model results from the Open LLM Leaderboard"
sourcecode = ["import_results.py"]
config = "import_results.py#model"

[import-all]

exec = "python import_batch.py"
description = "Import all available Open LLM model results"
sourcecode = ["import_results.py", "import_batch.py"]
config = "import_batch.py#preview"

[publish]

exec = "python publish.py"
description = "Publish board to Gage Live"
sourcecode = ["publish.py", "board.json"]
config = [
    "publish.py",
    "-#DATA_JSON"
]
